name = "nellys-legacy-project"
compatibility_date = "2024-09-23"
main = "worker.js"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "STORIES"
id = "7094dced89ea4fdea0665890d610409a"
